### ISSUE TITLE
warnings with yaml 2.1.19

### ISSUE THREAD

**Issue by IndrajeetPatil** [viking/r-yaml#56]
I downloaded the new version (2.1.19) of `yaml` that was released today and now every time I enter a project directory, I get these warnings:

![image](https://user-images.githubusercontent.com/11330453/39473775-80e41dc8-4d1e-11e8-9448-d721e9639bdd.png)

And the package build is no longer working:

```
Incorrect number of arguments (6), expecting 4 for 'unserialize_from_yaml'
Execution halted
Error in run(bin, args = real_cmdargs, stdout_line_callback = real_callback(stdout),  : 
  System command error
Calls: <Anonymous> ... with.default -> eval -> eval -> with_envvar -> force -> run
Execution halted

Exited with status 1.
```

It was working perfectly before the new version of `yaml` was installed so pretty sure there is something amiss with the new release.

**Comment by viking** [comment]
I can't reproduce your problem. Do you have a `.Rprofile` file that is running commands? Can you post the output from `sessionInfo()`? Thanks.

**Comment by IndrajeetPatil** [comment]
Sure!

![image](https://user-images.githubusercontent.com/11330453/39480117-430afeba-4d35-11e8-8df2-45d4223d2a0e.png)

I removed `2.1.18` and tried again and everything worked fine. Then downloaded `2.1.19` and tried again, and the same error. So this seems like something more systematic.

**Comment by viking** [comment]
There are a few things to consider.

1) Since you're using Windows, `install.packages()` will try to install a binary package if it can. Since the yaml package was just released, there is no binary package yet available. Usually it takes a couple of days for the Windows binary package to be built. You can check here to see if it's available (it is not available as of the time of this message): https://cran.r-project.org/web/packages/yaml/

2) R Studio will load from multiple package directories if you have upgraded your version of R. Packages that you installed while using an older version of R will get loaded by newer versions under certain circumstances. This may be causing problems here.

3) You're not using the latest version of R. This shouldn't really be an issue though, as I haven't been able to reproduce your issue in either R 3.5.0 or R 3.4.4.

When the Windows binary package is available for yaml 2.1.19, this issue may go away if you reinstall the package. I suggest using R's official program instead of R Studio to install the yaml package to test to see if this is still happening.

**Comment by IndrajeetPatil** [comment]
Thanks for the detailed instructions! Will wait for the binary version to become available on CRAN and will then get back to you about this.

**Comment by viking** [comment]
There's one more thing you can try in order to find the problem. From your error message, it looks like your `yaml.load` R function is from an old version, but the C function it's calling is from a newer version. This shouldn't really happen under normal circumstances.

It's possible that for some reason `yaml.load` has been redefined. If you run this: `getAnywhere('yaml.load')`, R will tell you if there is a conflict. If you see a message like this, for example:

```
> getAnywhere('yaml.load')
2 differing objects matching ‘yaml.load’ were found
in the following places
  .GlobalEnv
  package:yaml
  namespace:yaml
Use [] to view one of them
```
It means that `yaml.load` has been redefined. You may also want to check the output of `searchpaths()` to see what directories R is using.

**Comment by viking** [comment]
Hmm, interesting.

The fact that it shows `namespace:yaml` without `package:yaml` means that the `yaml.load` function was called without first loading the `yaml` package via `library(yaml)`. This happens when the function is called like this: `yaml::yaml.load(...)`. 

What happens if you explicitly load the package and call: `yaml.load('test')`?

**Comment by IndrajeetPatil** [comment]
This is what I get:
```
> library(yaml)
> yaml.load('test')
Error in .Call(C_unserialize_from_yaml, string, as.named.list, handlers,  : 
  Incorrect number of arguments (6), expecting 4 for 'unserialize_from_yaml'
```

**Comment by viking** [comment]
Ah, I actually got it backwards. The `yaml.load` R function is new but the C function is old. That means the yaml package module loaded into R is old. I'm guessing that's a result of the fact that the package was half installed.

I got a notice that the Windows binary package for CRAN has been built. It will be published within the next day or so. The best thing to do is just wait and reinstall, I think.

**Comment by IndrajeetPatil** [comment]
Perfect! Will keep you posted on what happens :)

**Comment by IndrajeetPatil** [comment]
Binaries for `2.1.19` are available on CRAN now. I downloaded the package and there are no longer any issues!

So you can close this thread now. Thanks!

**Comment by viking** [comment]
Glad to hear that it works. Cheers!

**Comment by ScientificProgrammer** [comment]
In case it helps, I was having the same problem as IndrajeetPatil when I tried to run
`devtools::install_github("viking/r-yaml")` from within RStudio. If I ran install.packages("viking/r-yaml") from within RStudio, the problem was resolved.

However, when I exited RStudio and ran `devtools::install_github("viking/r-yaml")` from within the standard R client, I still received the same compiler warnings, but the problem also went away.
