### ISSUE TITLE
Using special commands in YAML headers 

### ISSUE THREAD

**Issue by phargarten2** [viking/r-yaml#92]
I am writing a manuscript for _the R Journal_ with the aid of the **rticles** package. The journal asked me to use the `pkg{}` command to a title in a YAML header. However, upon running `rticles::r_journal()`, I ran into an error from **YAML**. 

```{r}
Error in yaml::yaml.load(..., eval.expr = TRUE) : 
  Scanner error: mapping values are not allowed in this context at line 1, column 17
Calls: <Anonymous> ... parse_yaml_front_matter -> yaml_load -> <Anonymous>
Execution halted
```

Please see https://github.com/rstudio/rticles/issues/363. 

I am unsure if this issue is something for you or for JJ Allaire and the other authors of  **rticles**.

**Comment by phargarten2** [comment]
StackOverflow documented that small formatting issues caused the error of `yaml_load()` to the error
[https://stackoverflow.com/questions/43527520/r-markdown-yaml-scanner-error-mapping-values]

**Comment by viking** [comment]
Thanks for your bug report. Here's how to reproduce the error:

```r
yaml.load("title: \\pkg{Foo}: A package about Foo")
```

Trying to load that string in Python also throws an error. The issue is that the string is not valid YAML. It can be corrected by doing this instead:

```r
yaml.load("title: '\\pkg{Foo}: A package about Foo'")
```

Quoting the string could interfere with the other packages you're using though, not sure.
